"""Initial

Revision ID: 053267134841
Revises: fd77296e9d38
Create Date: 2021-02-28 12:08:55.543695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053267134841'
down_revision = 'fd77296e9d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
