"""Initial

Revision ID: 1aa40475bb4d
Revises: 577c9922ab3b
Create Date: 2021-02-27 14:58:38.885951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa40475bb4d'
down_revision = '577c9922ab3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
