"""Initial

Revision ID: 36e583106003
Revises: 51c54ce55435
Create Date: 2021-02-28 12:14:49.676691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e583106003'
down_revision = '51c54ce55435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parent_wallet_new_column_key', 'parent_wallet', type_='unique')
    op.drop_constraint('parent_wallet_wif_key', 'parent_wallet', type_='unique')
    op.drop_column('parent_wallet', 'new_column')
    op.drop_column('parent_wallet', 'wif')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_wallet', sa.Column('wif', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.add_column('parent_wallet', sa.Column('new_column', sa.VARCHAR(length=111), autoincrement=False, nullable=False))
    op.create_unique_constraint('parent_wallet_wif_key', 'parent_wallet', ['wif'])
    op.create_unique_constraint('parent_wallet_new_column_key', 'parent_wallet', ['new_column'])
    # ### end Alembic commands ###
