"""Initial5

Revision ID: 37f61b2922e9
Revises: 50944894e1f1
Create Date: 2021-02-27 16:15:26.799953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f61b2922e9'
down_revision = '50944894e1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
