"""Initial4

Revision ID: 50944894e1f1
Revises: 1ef5ff3d9ec5
Create Date: 2021-02-27 16:14:25.833435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50944894e1f1'
down_revision = '1ef5ff3d9ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
