"""Initial

Revision ID: 51c54ce55435
Revises: 053267134841
Create Date: 2021-02-28 12:12:54.484873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51c54ce55435'
down_revision = '053267134841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_wallet', sa.Column('new_column', sa.String(length=111), nullable=False))
    op.create_unique_constraint(None, 'parent_wallet', ['new_column'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_wallet', type_='unique')
    op.drop_column('parent_wallet', 'new_column')
    # ### end Alembic commands ###
