"""Initial

Revision ID: 534ce8a73b80
Revises: 7604146f90ec
Create Date: 2021-02-28 16:07:08.647955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534ce8a73b80'
down_revision = '7604146f90ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('children_wallet_bip32_path_key', 'children_wallet', type_='unique')
    op.drop_constraint('children_wallet_path_key', 'children_wallet', type_='unique')
    op.drop_column('children_wallet', 'bip32_path')
    op.drop_column('children_wallet', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children_wallet', sa.Column('path', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('children_wallet', sa.Column('bip32_path', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_unique_constraint('children_wallet_path_key', 'children_wallet', ['path'])
    op.create_unique_constraint('children_wallet_bip32_path_key', 'children_wallet', ['bip32_path'])
    # ### end Alembic commands ###
