"""Initial9

Revision ID: 5495bb6fb029
Revises: c443789a1cb2
Create Date: 2021-02-28 12:04:33.680748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5495bb6fb029'
down_revision = 'c443789a1cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    op.drop_table('data2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data2',
    sa.Column('id2', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('somecolumn2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id2', name='data2_pkey')
    )
    op.create_table('data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('somecolumn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='data_pkey')
    )
    # ### end Alembic commands ###
