"""Initial

Revision ID: 5573287a2d27
Revises: 534ce8a73b80
Create Date: 2021-02-28 16:09:36.261623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5573287a2d27'
down_revision = '534ce8a73b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('children_wallet', sa.Column('bip32_path', sa.String(length=20), nullable=False))
    op.add_column('children_wallet', sa.Column('path', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('children_wallet', 'path')
    op.drop_column('children_wallet', 'bip32_path')
    # ### end Alembic commands ###
