"""Initial

Revision ID: 6c058b8d945f
Revises: bfdc485fd9ef
Create Date: 2021-02-28 12:17:13.721306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c058b8d945f'
down_revision = 'bfdc485fd9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('parent_wallet_wif_key', 'parent_wallet', type_='unique')
    op.drop_column('parent_wallet', 'wif')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_wallet', sa.Column('wif', sa.VARCHAR(length=70), autoincrement=False, nullable=False))
    op.create_unique_constraint('parent_wallet_wif_key', 'parent_wallet', ['wif'])
    # ### end Alembic commands ###
