"""Initial

Revision ID: 7604146f90ec
Revises: 6c058b8d945f
Create Date: 2021-02-28 12:17:35.603585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7604146f90ec'
down_revision = '6c058b8d945f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_wallet', sa.Column('wif', sa.String(length=130), nullable=False))
    op.create_unique_constraint(None, 'parent_wallet', ['wif'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_wallet', type_='unique')
    op.drop_column('parent_wallet', 'wif')
    # ### end Alembic commands ###
