"""Initial2

Revision ID: bee4f94794cc
Revises: e1759129900b
Create Date: 2021-02-27 15:09:38.856490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee4f94794cc'
down_revision = 'e1759129900b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('somecolumn', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data2',
    sa.Column('id2', sa.Integer(), nullable=False),
    sa.Column('data2', sa.String(), nullable=True),
    sa.Column('somecolumn2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id2')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data2')
    op.drop_table('data')
    # ### end Alembic commands ###
