"""Initial

Revision ID: bfdc485fd9ef
Revises: 36e583106003
Create Date: 2021-02-28 12:15:09.571932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfdc485fd9ef'
down_revision = '36e583106003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_wallet', sa.Column('wif', sa.String(length=70), nullable=False))
    op.create_unique_constraint(None, 'parent_wallet', ['wif'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parent_wallet', type_='unique')
    op.drop_column('parent_wallet', 'wif')
    # ### end Alembic commands ###
