"""Initial6

Revision ID: cc38000cd718
Revises: 37f61b2922e9
Create Date: 2021-02-27 16:27:13.354178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc38000cd718'
down_revision = '37f61b2922e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('children_wallet',
    sa.Column('address', sa.String(length=34), nullable=False, foreign_key='parent_wallet.address'),
    sa.Column('bip32_path', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=10), nullable=False),
    sa.Column('xpublic_key', sa.String(length=111), nullable=False),
    sa.PrimaryKeyConstraint('bip32_path', 'path'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('bip32_path'),
    sa.UniqueConstraint('path'),
    sa.UniqueConstraint('xpublic_key')
    )
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('somecolumn', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data2',
    sa.Column('id2', sa.Integer(), nullable=False),
    sa.Column('data2', sa.String(), nullable=True),
    sa.Column('somecolumn2', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id2')
    )
    op.create_table('parent_wallet',
    sa.Column('address', sa.String(length=34), nullable=False),
    sa.Column('coin', sa.String(length=5), nullable=False),
    sa.Column('private_key', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.String(length=130), nullable=False),
    sa.Column('seed', sa.String(length=130), nullable=False),
    sa.Column('wif', sa.String(length=60), nullable=False),
    sa.Column('xprivate_key', sa.String(length=111), nullable=False),
    sa.Column('xpublic_key', sa.String(length=111), nullable=False),
    sa.Column('xpublic_key_prime', sa.String(length=111), nullable=False),
    sa.PrimaryKeyConstraint('address'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('private_key'),
    sa.UniqueConstraint('public_key'),
    sa.UniqueConstraint('seed'),
    sa.UniqueConstraint('wif'),
    sa.UniqueConstraint('xprivate_key'),
    sa.UniqueConstraint('xpublic_key'),
    sa.UniqueConstraint('xpublic_key_prime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parent_wallet')
    op.drop_table('data2')
    op.drop_table('data')
    op.drop_table('children_wallet')
    # ### end Alembic commands ###
