"""Initial

Revision ID: e1759129900b
Revises: 1aa40475bb4d
Create Date: 2021-02-27 15:06:32.557249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1759129900b'
down_revision = '1aa40475bb4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
