"""Initial9

Revision ID: fd77296e9d38
Revises: 5495bb6fb029
Create Date: 2021-02-28 12:06:26.841095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd77296e9d38'
down_revision = '5495bb6fb029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
